MERGE INTO GENRE (GENRE_ID, GENRE_NAME)
VALUES (1, 'COMEDY'),
       (2, 'DRAMA'),
       (3, 'CARTOON'),
       (4, 'THRILLER'),
       (5, 'DOCUMENTARY'),
       (6, 'ACTION');
MERGE INTO MPA (MPA_ID, MPA_NAME)
VALUES (1, 'G'),
       (2, 'PG'),
       (3, 'PG13'),
       (4, 'R'),
       (5, 'NC17');
MERGE INTO STATUS (STATUS_ID, NAME)
VALUES (1, 'FRIEND'),
       (2, 'REQUIRED');
MERGE INTO FILMS (FILM_ID, FILM_NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID)
VALUES (1, 'TERMINATOR', 'BLA BLA BLA', '1992-01-01', 100, 4),
       (2, 'FOREST GUMP', 'BLA BLA', '1998-01-10', 120, 1),
       (3, 'DRACULA', 'BLA', '1985-05-05', 110, 5);
MERGE INTO FILM_GENRE (FILM_GENRE_ID, FILM_ID, GENRE_ID)
VALUES (1, 1, 6),
       (2, 2, 2),
       (3, 3, 4);
MERGE INTO USERS (USER_ID, USER_NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES (1, 'TOM', 'TOM123', 'TOM@MAIL.RU', '1986-09-11'),
       (2, 'TONY', 'TONY123', 'TONY@MAIL.RU', '1985-05-21'),
       (3, 'BILLY', 'BILLY123', 'BILLI@GMAIL.COM', '1984-12-15');
MERGE INTO USER_LIKES (USER_LIKES_ID, FILM_ID, USER_ID)
VALUES (1, 1, 1),
       (2, 1, 2),
       (3, 2, 3),
       (4, 3, 2);
MERGE INTO FRIEND_LIST (FRIEND_LIST_ID, USER_ID, FRIEND_ID, STATUS_ID)
VALUES (1, 1, 2, 1),
       (2, 1, 3, 2),
       (3, 3, 2, 2);